twig:
    default_path: '%kernel.project_dir%/templates'
    paths:
        '%kernel.project_dir%/templates/test': 'test'
        '%kernel.project_dir%/templates/test_result': 'test_result'
        '%kernel.project_dir%/templates/error': 'error'

when@test:
    twig:
        strict_variables: true
